version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27016:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: